<a href="https://colab.research.google.com/github/Hamilton-at-CapU/comp215/blob/main/lessons/week07_numpy_1D_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy:  1D array (vector) operations
[numpy array](https://numpy.org/doc/stable/reference/arrays.html) objects come with very powerful built-in vector operations.
These allow you to perform an operation on every element of the vector without any explicit iteration. E.g.,
 - simple map operations (to map one vector onto another the same size) using python's math operators
 - vector x scalar and vector x vector operations using math operators
 - create a boolean vector using comparison operators;
 - vector indexing and powerful vector filtering operations using python's indexing operator, $[ ]$

This makes for very concise and efficient code, but the code is a bit deceptive because unless you are cognizant that a variable refers to a numpy array, there is often no clue that a vector operation is being performed.  Let's look at some examples...


In [ ]:
import numpy as np

## Create a 1D array
 * simple: define it using a list or tuple or any other sequence type (but not a generator!);
 * general: define it by supplying its length;
 * random: filled with random values;
Notice that in some way we must always pre-define the vector's length.

In [ ]:
vector = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])

ones = np.ones(9, dtype='uint8')
rand = np.random.randint(2, size=9, dtype='uint8')
vector, ones, rand

(array([9, 8, 7, 6, 5, 4, 3, 2, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 1, 0, 1, 0, 1, 1, 1, 1], dtype=uint8))

## Vector x Scalar operations
numpy array class defines all math and comparison operators.
Confusion arises here b/c the code itself does not indicate there is a vector operation being done - you have to know!

In [ ]:
double = vector * 2
twos = ones + 1
alive = rand == 1
double, twos, alive

(array([18, 16, 14, 12, 10,  8,  6,  4,  2]),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=uint8),
 array([ True,  True, False,  True, False,  True,  True,  True,  True]))

## Vector x Vector operations
All operators also work when both arguments are arrays, in this case operations are done pair-wise on matching elements.
The 2 arrays must have the same dimensions!

In [ ]:
squares = vector * vector
threes = ones + twos
filtered = rand * vector
squares, threes, filtered

(array([81, 64, 49, 36, 25, 16,  9,  4,  1]),
 array([3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=uint8),
 array([9, 8, 0, 6, 0, 4, 3, 2, 1]))

## Logical operators
numpy does not re-define python's built-in logical operators `and`, `or`, `not`
But it does define the "bitwise" operators, bitwise and `&`, bitwise or `|` and bitwise not '~'.
With care, these can be used to implement whole-matrix logical operations...
**Tips**: both operands should by `bool` or `0`/`1` valued arrays (or you better really understand bitwise operators!).
     Watch your precedence -- bitwise operators are very low precedence!

In [ ]:
try:
    ones and twos  # can't use built-in logical operators on arrays!
except ValueError as e:
    print('Error:', e)

# Use "bit-wise" operators with care - only on `bool` or binary (0/1) valued arrays!
fitlered2 = alive & vector!=0
big_and_alive = (vector > 5) & alive
not_alive = ~alive
alive, fitlered2, big_and_alive, not_alive

Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


(array([ True,  True, False,  True, False,  True,  True,  True,  True]),
 array([ True, False, False, False, False, False,  True, False,  True]),
 array([ True,  True, False,  True, False, False, False, False, False]),
 array([False, False,  True, False,  True, False, False, False, False]))

## Vector indexing
Perhaps one of the most powerful numpy array operations is the ability to use the values of one array as indexes to lookup values in another array.
For this operation the arrays can be different sizes and shapes, but you need to be clear about which array is the lookup table and which is the indexes!

In [ ]:
month_names = np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
month_nums = np.random.randint(low=1, high=12, size=9)
month_nums, month_names[month_nums-1]

(array([ 7,  3, 11,  1,  2,  4,  2,  2,  3]),
 array(['Jul', 'Mar', 'Nov', 'Jan', 'Feb', 'Apr', 'Feb', 'Feb', 'Mar'],
       dtype='<U3'))

### Filter with Boolean indexes
By using an array of booleans, you can filter out a set of elements from another array with the same shape.

In [ ]:
even_squares = squares[squares%2==0]
squares, even_squares, squares[alive]

(array([81, 64, 49, 36, 25, 16,  9,  4,  1]),
 array([64, 36, 16,  4]),
 array([81, 64, 36, 16,  9,  4,  1]))

Notice you get back a 1D array of filtered elements.  These can act as references back to elements in the original array.
This allows us to use a scalar assignment to update elements of the original vector that meet some criteria ...

In [ ]:
vec_copy = vector.copy()
vec_copy[~alive] = 0
vector, alive, vec_copy

(array([9, 8, 7, 6, 5, 4, 3, 2, 1]),
 array([ True,  True, False,  True, False,  True,  True,  True,  True]),
 array([9, 8, 0, 6, 0, 4, 3, 2, 1]))